### ISSUE TITLE
Beste Caspar. Dit is dus de manier van communiceren? Via Github. Helder en handig. Als je dit bericht ontvangt, is het me gelukt je te bereiken. Laat even weten.

### ISSUE THREAD

**Issue by herberthoijtink** [cjvanlissa/bain#4]

**Comment by cjvanlissa** [comment]
Min of meer! Dit is een "takenlijstje". Je kan taken aan mensen toewijzen, en discussieren indien nodig. Je kan ook aan deze taken refereren als je nieuwe code uploadt die één van de taken oplost! Bijvoorbeen het issue "Comparability", daar gaan wij vrijdag even over praten, en daarna schrijf ik wat code die de check voor comparable hypotheses correct (en efficienter dan nu) implementeert :)
