### ISSUE TITLE
Few tests fail on ppc32: [ FAIL 6 | WARN 0 | SKIP 0 | PASS 850 ]

### ISSUE THREAD

**Issue by barracuda156** [cjvanlissa/bain#41]
```

R version 4.2.3 (2023-03-15) -- "Shortstop Beagle"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: powerpc-apple-darwin10.8.0 (32-bit)

> rm(list=ls())
> library(testthat)
> library(lavaan)
This is lavaan 0.6-15
lavaan is FREE software! Please report any bugs.
> library(bain)
> test_check("bain")
[ FAIL 6 | WARN 0 | SKIP 0 | PASS 850 ]

══ Failed tests ════════════════════════════════════════════════════════════════
── Failure ('test-J.R:209:28'): bain default ───────────────────────────────────
y$fit$Fit[1] not equal to mean(sampf).
1/1 mismatches
[1] 0.849 - 0.866 == -0.0166
── Failure ('test-complement.R:136:18'): fc ────────────────────────────────────
c(results2$fit$Fit[4], results2$fit$Com[4]) not equal to c(...).
1/2 mismatches
[1] 0 - 0.00886 == -0.00886
── Failure ('test-complement.R:205:18'): fc ────────────────────────────────────
c(results2$fit$Fit[6], results2$fit$Com[6]) not equal to c(...).
1/2 mismatches
[1] 0 - 0.00883 == -0.00883
── Failure ('test-complement.R:291:18'): fc ────────────────────────────────────
c(results2$fit$Fit[5], results2$fit$Com[5]) not equal to c(...).
1/2 mismatches
[2] 0.388 - 0.397 == -0.00929
── Failure ('test-complement.R:503:18'): fc ────────────────────────────────────
c(results2$fit$Fit[5], results2$fit$Com[5]) not equal to c(0, 0).
1/2 mismatches
[2] 0.0114 - 0 == 0.0114
── Failure ('test-complement.R:639:18'): fc ────────────────────────────────────
c(results2$fit$Fit[4], results2$fit$Com[4]) not equal to c(...).
1/2 mismatches
[1] 0.394 - 0.374 == 0.0195

[ FAIL 6 | WARN 0 | SKIP 0 | PASS 850 ]
Error: Test failures
Execution halted
```

**Comment by mihaiconstantin** [comment]
To rule out false positives in the numerical procedures, maybe we could consider rounding the parameters in the `expect_equal` call to a specific decimal (i.e., essentially saying that differences after the $i\text{-th}$ decimal are not important), e.g.: 

https://github.com/cjvanlissa/bain/blob/7b4c104aaa99bf95525d30465457b58e0a4a573c/tests/testthat/test2-J.R#L30-L33

However, the output above shows differences in the second and third decimals. This doesn't seem desirable. Do you observe the same on repeated test runs?

**Comment by barracuda156** [comment]
@mihaiconstantin Thank you for responding.
Yeah, it clearly should not differ in the third digit on correct code. I think ppc on 32 bit has about 16 digits precision (need to check IBM documentation).
I have encountered rounding errors with a few other R packages (like, maybe about a dozen out of 1000+, hard to say exactly). Not really sure what is going on in these cases.

We test quite a number of math and scientific ports (unrelated to R), and if precision were that bad on cpu or OS, everything would have failed miserably :) It is not the case. Normally precision works as expected, at times I have seen occasional divergence around 10th digit.

Maybe something is broken in R itself? I have no idea, to be honest, how it does rounding.

**Comment by mihaiconstantin** [comment]
Thanks for the context! Can you add the session information as well?

```r
# Session information.
sessionInfo()
```

**Comment by barracuda156** [comment]
@mihaiconstantin Give me a few min, I will run tests again on PPC and also on i386, that clarify a bit what fails.

**Comment by barracuda156** [comment]
@mihaiconstantin Maybe leave the issue open but mark as low priority? (I certainly do not claim it to be otherwise.) Unless, of course, you are sure that the bug is either in `R` or in `lavaan` – then it should be fixed there.

Update on results: on 10.6.8 i386 all tests pass, so we can safely rule out 32-bitness or macOS SDK as being the cause of the problem.
```
R version 4.3.0 (2023-04-21) -- "Already Tomorrow"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: i386-apple-darwin10.8.0 (32-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> rm(list=ls())
> library(testthat)
> library(lavaan)
This is lavaan 0.6-15
lavaan is FREE software! Please report any bugs.
> library(bain)
> test_check("bain")
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 856 ]
> 
> proc.time()
   user  system elapsed 
229.326   1.089 230.495 
```

My current thought: something (`R`, `lavaan` or `bain`) does not handle rounding mode for powerpc correctly.
Somewhat less likely (IMO) – a bug in `gfortran`, if it is used is tests in question.

P. S. `gfortran` is not in perfect status on powerpc (not sure about i386), but majority of tests pass. This I can say for sure, since I work on fixing it :)
At the moment, for gcc 12.3.0:
```
		=== gfortran Summary ===

# of expected passes		65808
# of unexpected failures	55
# of unexpected successes	12
# of expected failures		286
# of unsupported tests		374
```

(Will update with `bain` PPC tests log soon, they are still running. I am away from a fast machine, so it takes somewhat long.)
